### PR TITLE
Postgres lob fix

### PR DESCRIPTION
**Pull request by hannakoppelaar**
This pr fixes the Lob issue with PostgreSQL: we now have the same semantics as before, when we had the materialized_clob annotation. I've tested it with MySQL as well. Hopefully it doesn't break Oracle support.

It also fixes the odd pagination behaviour under PostgreSQL by letting hibernate load associations lazily. Why hibernate behaves so differently depending on the db platform is a scary question that I will ignore for now.

### CODE REVIEW

**Comment by leefrank9527** [comment]
Permission.java:

**Comment by hannakoppelaar** [comment]
>     3. The length limitation of "PE_COPYRIGHT_STATEMENT", "PE_COPYRIGHT_URL", "PE_SPECIAL_REQUIREMENTS" do not work. I could input text contents larger than their length limitation. Such as: @column(name = "PE_SPECIAL_REQUIREMENTS", length = 2048). I can input 3946 bytes.

Yeah, the length attribute on @Column is only used when using hibernate to generate DDL statements. So it's basically useless to us now. If we want to check input length here we should use the @Size annotation from the Bean validation API.

**Comment by leefrank9527** [comment]
@hannakoppelaar About the pagination rows. I am sorry about I counted a wrong number. It's correctly showed 10 lines using a page size of 10. 
I would check for Oracle today. If we can limit the length with @Size annotation and it can do work for Oracle, then we can close the PR.

**Comment by hannakoppelaar** [comment]
@leefrank9527 I've converted all length attributes to SIze annotations. While I was I at it, I changed the nullable = false attributes to NotNull annotations (for the same reason) and I removed a number of DDL-only attributes: unique, columnDefinition and foreignKey.

I've written a little program to do this, so I hope I haven't introduced any odd regressions. At first glance everything looked okay to me.

Let me know if this works with Oracle.

**Comment by leefrank9527** [comment]
**For Oracle:**
1. The pagination does work well.
2. The fields of text type can be saved and retrieved from DB correctly.
3. The annotation of @Size can do work, but the alarm message presented on UI is too long. **Here there is another remaining issue of component webcurator-webapp: some validators aren't triggered to check the length of fields.** I would go through and fix the issue.
    With the length is checked at webcurator-webapp side. @Size annotation could not be reached.

**For PostgreSQL:**
As I mentioned in the 1st comment that "Some fields aren't allowed to input more that 2001 bytes". I would double check it. I don't think there is a problem here. Maybe my text editor doesn't include  newline chars.

**Comment by leefrank9527** [comment]
@hannakoppelaar 
**For PostgreSQL:** : The annotation of @SiZe can do work as well. 

@obrienben: Is it fine that I would add a branch to fix validator missing issue for webcurator-webapp?

**Comment by hannakoppelaar** [comment]
Okay thanks @leefrank9527! Does that mean this is ready to be merged?

**Comment by leefrank9527** [comment]
@hannakoppelaar @obrienben :  Exactly. It's ready for merging from my perspective.

**Comment by obrienben** [comment]
Thanks @hannakoppelaar @leefrank9527 I'll test this branch on our DEV environment, which is Oracle.

**Comment by obrienben** [comment]
Initial testing is good with Oracle

**Comment by obrienben** [comment]
After some more testing, I'm finding errors when deleting a Target schedule, and then saving a Target. This is occurring with Mysql and Oracle. Can you both check if this happens for you?

Mysql:
`Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Cannot delete or update a parent row: a foreign key constraint fails (`db_wct`.`target_instance`, CONSTRAINT `FK_TI_TARGET_ID` FOREIGN KEY (`TI_TARGET_ID`) REFERENCES `abstract_target` (`AT_OID`))`

Oracle:
`Caused by: java.sql.SQLIntegrityConstraintViolationException: ORA-02292: integrity constraint (DB_WCT.FK_TI_TARGET_ID) violated - child record found`

**Comment by hannakoppelaar** [comment]
@obrienben Yeah, I can reproduce that error. I'll look into it.

**Comment by hannakoppelaar** [comment]
@obrienben This issue has not been introduced on this branch, it's already in master. I'll create a separate PR to fix this.

**Pull request merged**
